### ISSUE TITLE
Verify all unit labels are correct

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#115]
Also, feet is good to list, but the spreadsheet us set up in inches. Confirm this if this should change to inches or is actually calculating feet.

**Comment by CNimmo16** [comment]
1 and 2 updated in metadata database. Walls, fences and gates are currently specified as length x width x height. Should it just be two dimensions instead, and if so width x height or length x height?

**Comment by pjconrad** [comment]
Walls, fences and gates should be length (feet) x width (inches) x height (inches)
![image](https://user-images.githubusercontent.com/46090868/64202806-dc443180-ce46-11e9-9045-6d1311ed9b90.png)

**Comment by pjconrad** [comment]
Cameron - note that these are unit labels that need to be confirmed. They should be what is specified in the spreadsheet for the green input boxes.

**Comment by CNimmo16** [comment]
In that case those units for walls, fences and gates are already correct in database. The reason this is not correctly shown on the live site is due to a typo in the existing code, pull request #125 includes a fix for this. Please refer to [http://lcc-stage-cameron.surge.sh](http://lcc-stage-cameron.surge.sh) for preview. I suspect this same typo would have been the cause of any other discrepancies in displayed dimensions/units, but will go through each tomorrow to check.

**Comment by edanweis** [comment]
Picked up by Cameron.
