### ISSUE TITLE
User stories

### ISSUE THREAD

**Issue by edanweis** [edanweis/LCC#8]
Examples

1. As a **landscape architect** coming from a blog post link, I want to **calculate the CF of a project** so that I can decide whether to include it in a submission.

2. As a **landscape architect** coming from an invite link, I want to **see how our project performs** compared to other studios so that **I can present the results and make my project look good**

3. As a **Timber supplier** responding to an email invite, I want to **see how I can generate leads** from the platform so that **I can grow my business**

etc.

**Comment by pjconrad** [comment]
1. As a landscape architect coming from a blog post link, I want to use the tool so that I know how to decrease my site's carbon footprint, increase sequestration, and offset my footprint faster. 

2. As a landscape architect coming from an article link, I want to see how my project's footprint compares to other competitors. 

3. As a landscape architect hearing about the initiative at a conference, I want to find products that will help me lower my carbon footprint. 

4. As a landscape architect wanting to make a difference in climate change, I want to contribute to the overall professions goals to reduce emissions and increase sequestration. 

5. As a landscape architect wanting to make a difference in climate change, I want to contribute to the overall professions goals to reduce emissions and increase sequestration. 

6. ... I want to know what materials have the lowest carbon footprints so I can use those. 
7. ... I want to know what materials have the highest carbon footprints so I can avoid those. 
8. ... I want to know what trees and plants sequester the most carbon and which ones are the fastest. 
9. ... I want to know how to reduce emissions through maintenance practices. 
10. .I want to know how my contribution will add to a greater goal for the profession. 
11. .I want to know how much my footprint has decreased, and sequestration has increased so I can show/tell my client, my colleagues, and my family. 
12. I want to understand why carbon footprints and sequestration matters. 
13. I want to see how our project performs compared to other studios.
14. I want to get my score for SITES/LEED credits. 

13. As a Timber supplier responding to an email invite, I want to see how I can generate new business from the platform
14. As a developer
15. As a planner
16. As a student
17. As a homeowner

In progress ...

**Comment by pjconrad** [comment]
... I want to do ... (PC to add)

**Comment by edanweis** [comment]
![image](https://user-images.githubusercontent.com/2130136/51081700-ea273400-1749-11e9-9641-55d39f22ced6.png)

**Comment by edanweis** [comment]
@pjconrad I've moved the shortlist from the [Google sheet](https://docs.google.com/spreadsheets/d/1KTCqEsFweiYyCSkns9hxTC7yY2Wp8hL5jncwZsGApjw/edit#gid=69377701) to the [User Stories GitHub project](https://github.com/edanweis/LCC/projects/2). Feel free to add columns (stories) and add a card under each column to expand on the story with realism and specifics.
